// ========================================
// CENTRALIZED IMPORTS
// ========================================

require("events").EventEmitter.defaultMaxListeners = 500
process.setMaxListeners(500)
require("../../settings")

const config = require("../../config.js")
const {
  pino,
  Boom,
  fs,
  simple,
  chalk,
  color,
  FileType,
  path,
  axios,
  _,
  uncache,
  nocache,
  yargs,
  moment,
  PhoneNumber,
  imageToWebp,
  videoToWebp,
  writeExifImg,
  writeExifVid,
  smsg,
  isUrl,
  generateMessageTag,
  getBuffer,
  getSizeMedia,
  fetch,
  sleep,
  reSize,
  XeonBotIncConnect,
  delay,
  SimpleStore,
  PHONENUMBER_MCC,
  makeCacheableSignalKeyStore,
  useMultiFileAuthState,
  DisconnectReason,
  fetchLatestBaileysVersion,
  generateForwardMessageContent,
  prepareWAMessageMedia,
  generateWAMessageFromContent,
  generateMessageID,
  downloadContentFromMessage,
  jidDecode,
  proto,
  Browsers,
  NodeCache,
  Pino,
  readline,
  parsePhoneNumber,
  makeWASocket,
  dotenv,
  store,
  custom,
  saveAllMessages,
  loadMessages,
  allMessages,
  createMessagesTable,
  findMessageById, 
   getAllMessages,
    deleteMessageById,
   deletedMessages,
  processedDeletedMessages,
  pool,
    testConnection,
  getAggregateVotesInPollMessage,
  generateWAMessage,
  areJidsSameUser,
  globalGroupCache,
    downloadMediaMessage, getContentType
} = require("../../lib/logs.js")

const { StringSession, restoreSession, saveToEnv, sendSessionToWhatsApp } = require("../../lib/filewatcher.js")
const { toPTT, toAudio } = require("../../lib/converter")

// Protocol message types
const PROTOCOL_MESSAGE_TYPES = {
  REVOKE: 0,
  EPHEMERAL_SETTING: 1,
  EPHEMERAL_SYNC_RESPONSE: 2,
  HISTORY_SYNC_NOTIFICATION: 3,
  APP_STATE_SYNC_KEY_SHARE: 4,
  APP_STATE_SYNC_KEY_REQUEST: 5,
  MSG_FANOUT_BACKFILL_REQUEST: 6,
  INITIAL_SECURITY_NOTIFICATION_SETTING_SYNC: 7,
  APP_STATE_FATAL_EXCEPTION_NOTIFICATION: 8,
  SHARE_PHONE_NUMBER: 9,
  MESSAGE_EDIT: 14,
  PEER_DATA_OPERATION_REQUEST_MESSAGE: 16,
  PEER_DATA_OPERATION_REQUEST_RESPONSE_MESSAGE: 17,
}

module.exports = {
  config,
  pino,
  Boom,
  fs,
  simple,
  chalk,
  color,
  FileType,
  path,
  axios,
  _,
  uncache,
  nocache,
  yargs,
  moment,
  PhoneNumber,
  imageToWebp,
  videoToWebp,
  writeExifImg,
  writeExifVid,
  smsg,
  isUrl,
  generateMessageTag,
  getBuffer,
  getSizeMedia,
  fetch,
  sleep,
  reSize,
  XeonBotIncConnect,
  delay,
  SimpleStore,
  PHONENUMBER_MCC,
  makeCacheableSignalKeyStore,
  useMultiFileAuthState,
  DisconnectReason,
  fetchLatestBaileysVersion,
  generateForwardMessageContent,
  prepareWAMessageMedia,
  generateWAMessageFromContent,
  generateMessageID,
  downloadContentFromMessage,
  jidDecode,
  proto,
  Browsers,
  NodeCache,
  Pino,
  readline,
  parsePhoneNumber,
  makeWASocket,
  dotenv,
  store,
  custom,
  saveAllMessages,
  loadMessages,
  allMessages,
  createMessagesTable,
  processedDeletedMessages,
  pool,
  getAggregateVotesInPollMessage,
  generateWAMessage,
  areJidsSameUser,
  globalGroupCache,
  StringSession,
  restoreSession,
  saveToEnv,
  sendSessionToWhatsApp,
  toPTT,
    deleteMessageById,
    testConnection,
  toAudio,
      findMessageById, 
   getAllMessages,
   deletedMessages,
  PROTOCOL_MESSAGE_TYPES,
    downloadMediaMessage, getContentType
}
